source 'https://github.com/CocoaPods/Specs.git'
# platform :ios, '9.0'

target 'Voice_copy' do


	pod 'LookinServer', :configurations => ['Debug']

	pod 'SnapKit'
  
  pod 'RSKImageCropper'
  
  pod 'TZImagePickerController'

  pod "YYModel"
  
  pod 'IQKeyboardManagerSwift'

  pod "SDWebImage"
  
  pod "GCDWebServer", "~> 3.0"
  
  pod "Moya"
  pod 'ReachabilitySwift'
  pod 'CryptoSwift', '~> 1.3.3'
  pod 'Result', '~> 5.0'


end
