source 'https://github.com/CocoaPods/Specs.git'
# platform :ios, '9.0'

target 'Voice_copy' do


	pod 'LookinServer', :configurations => ['Debug']

	pod 'SnapKit'
  
  pod 'RSKImageCropper'
  
  pod 'TZImagePickerController'

  pod "YYModel"

end
